-- 고양이와 개는 몇 마리 있을까?
SELECT ANIMAL_TYPE, COUNT(*) AS 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 동명 동물 수 찾기
-- 방법1
SELECT NAME, COUNT(NAME) 
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL
GROUP BY NAME HAVING COUNT(NAME) >= 2
ORDER BY NAME

-- 방법2
SELECT NAME, COUNT(NAME) AS COUNT_TWICE
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME HAVING COUNT_TWICE >= 2
ORDER BY NAME

-- 입양 시각 구하기(1)
-- 방법1
SELECT SUBSTRING(DATETIME, 12, 2) AS HOUR, COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR 
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR

-- 방법2
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR

-- 입양 시각 구하기(2)
